### ISSUE TITLE
Project Informations

### ISSUE THREAD

**Issue by pidgeon777** [spellingmistake/cscope#1]
Hello, I'm curious to hear more about this project.

How could you build it in Windows 10, does any screenshot exist?

Also, which should be the features of this tool?

**Comment by spellingmistake** [comment]
See [cscope main page](http://cscope.sourceforge.net/) for a potential Windows™ build.

> Also, which should be the features of this tool?

_Cscope is a developer's tool for browsing source code_ (from [cscope main page](http://cscope.sourceforge.net/))

This is not an issue!
